apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary
spec:
  selector:
    matchLabels:
      app: dictionary
  replicas: 1
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
        - name: dictionary
          image: surfadvisor/dictionary:latest
          ports:
            - containerPort: 5001

          envFrom:
            - secretRef:
                name: dict-dynamodb-secrets
          readinessProbe:
            httpGet:
              path: /dictionary/health-check
              port: 5001
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /dictionary/health-check
              port: 5001
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: surf-dictionary
spec:
  selector:
    app: dictionary
  ports:
    - name: http
      port: 5001
      targetPort: 5001
      protocol: TCP
  type: NodePort
