select merge_dict_item('MAIN_SCREEN_OPTIONS', 'LOGOUT', 'EN', 'Logout');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'LOGOUT', 'PL', 'Wyloguj');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'USER_PROFILE', 'EN', 'Edit Profile');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'USER_PROFILE', 'PL', 'Edytuj Profil');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MANAGE', 'EN', 'Manage');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MANAGE', 'PL', 'Administracja');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'BADGES', 'EN', 'Badges');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'BADGES', 'PL', 'Odznaki');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MAIN_COMPETITIONS', 'EN', 'Main Competitions');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MAIN_COMPETITIONS', 'PL', 'Konkurencje Główne');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'SIDE_MISSIONS', 'EN', 'Side Missions');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'SIDE_MISSIONS', 'PL', 'Misje Poboczne');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'RANKING', 'EN', 'Ranking');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'RANKING', 'PL', 'Ranking');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'ZONGLER', 'EN', 'Żongler');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'ZONGLER', 'PL', 'Żongler');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'BET', 'EN', 'Bet');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'BET', 'PL', 'Zakład');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MEDAL', 'EN', 'Medal');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'MEDAL', 'PL', 'Medal');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'REPORT_MAIN_COMPETITION', 'EN', 'Submit Main Competition');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'REPORT_MAIN_COMPETITION', 'PL', 'Konkurencja Główna');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'PROFESSOR_RATE', 'EN', 'Professor Rate');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'PROFESSOR_RATE', 'PL', 'Ocena Profesora');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'REPORT_SIDE_MISSION', 'EN', 'Report Side Mission');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'REPORT_SIDE_MISSION', 'PL', 'Raport Misji Pobocznej');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'JUDGE_RATE', 'EN', 'Rate Mission');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'JUDGE_RATE', 'PL', 'Oceń Misję');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'PLAYING_USERS', 'EN', 'Wizards');
select merge_dict_item('MAIN_SCREEN_OPTIONS', 'PLAYING_USERS', 'PL', 'Czarodzieje');
